
joint_state_broadcaster_fcs4hand2310:
  ros__parameters:
    joints: [ hndj00, hndj01, hndj10, hndj11 ]
    interfaces: [ position ]

joint_trajectory_controller_fcs4hand2310:
  ros__parameters:
    joints: [ hndj00, hndj01, hndj10, hndj11 ]
    command_interfaces: [ position ]
    state_interfaces:   [ position ]

    state_publish_rate:   2.0 # Defaults to 50
    action_monitor_rate:  2.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: false
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

